version: '3.8'
services:
  nextjs:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: .
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next