name: Build and Push to Azure

on:
  push:
    paths:
      - hotel-information-agent/**
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: DverseHotelInformationAgentApp
  IMAGE_NAME: dversehotelinformationagentcontainer.azurecr.io/app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: hotel-information-agent
    steps:
      - uses: actions/checkout@v4

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.RENO_REGISTRY_USERNAME }}
          password: ${{ secrets.RENO_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.HOTEL_INFO_AZURE_PUBLISH_PROFILE }}
          images: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'