name: Build, Push and Deploy to ACR and Web App

env:
  AZURE_WEBAPP_NAME: DVerseGoogleSearchAgent  # set this to the name of your Azure Web App

on:
  push:
    paths:
      - GoogleSearchAgent/**
      - .github/workflows/PushAzureContainerRegistry.GoogleSearchAgent.yml
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: GoogleSearchAgent
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: dversegooglesearchagent.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t dversegooglesearchagent.azurecr.io/myapp:${{ github.sha }} .
          docker push dversegooglesearchagent.azurecr.io/myapp:${{ github.sha }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.GOOGLE_SEARCH_AGENT_AZURE_PUBLISH_PROFILE }}
          images: 'dversegooglesearchagent.azurecr.io/myapp:${{ github.sha }}'

