name: Build and Push to Azure

on:
  push:
    paths:
      - hotel-information-agent/**
    branches:
      - main

jobs:  
  build_and_push:  
    runs-on: ubuntu-latest  
    defaults:  
      run:  
        shell: bash  
        working-directory: hotel-information-agent  
    steps:  
      - uses: actions/checkout@v4 
  
      - uses: azure/docker-login@v1  
        with:  
          login-server: dversehotelinformationagentcontainer.azurecr.io  
          username: ${{ secrets.RENO_REGISTRY_USERNAME }}  
          password: ${{ secrets.RENO_REGISTRY_PASSWORD }}  
  
      - name: Build and Push Docker image  
        run: |  
          docker build -t dversehotelinformationagentcontainer.azurecr.io/app:${{ github.sha }} .  
          docker push dversehotelinformationagentcontainer.azurecr.io/app:${{ github.sha }}
          
  deploy:
    runs-on: ubuntu-latest  
    needs: build_and_push
    steps:  
      - name: Deploy to Azure Web App  
        uses: azure/webapps-deploy@v2  
        with:  
          app-name: 'DVerseHotelInfoAgent'  
          publish-profile: ${{ secrets.HOTEL_INFO_AZURE_PUBLISH_PROFILE }}  
          images: 'dversehotelinformationagentcontainer.azurecr.io/app:${{ github.sha }}'